package com.qiaoqiao.settings

const val RC_CAMERA_PERMISSIONS = 123
const val RC_READ_EXTERNAL_STORAGE_PERMISSIONS = RC_CAMERA_PERMISSIONS + 1
const val RC_WRITE_EXTERNAL_STORAGE_PERMISSIONS = RC_READ_EXTERNAL_STORAGE_PERMISSIONS + 1
const val RC_FINE_LOCATION_PERMISSIONS = RC_WRITE_EXTERNAL_STORAGE_PERMISSIONS + 1